![](http://osloyi5le.bkt.clouddn.com/ML%E6%A1%88%E4%BE%8Bbanner.jpg)

# 使用房价预测经典案例练习回归树建模和随机森林建模流程
作者：寒小阳、助教：haoshuai714

## 案例背景

描述案例背景：

1.本案例的目的是让大家更加了解随机森林建模的过程；

2.本案例采用经典的房屋价格数据集来进行学习；

3.本案例将回归树训练的结果和随机森林回归树的结果进行了对比；

## 基础知识

1.决策树算法基本原理；

2.随机森林的基本原理；

3.回归树算法原理和随机森林算法原理；

4.重点：最后补充随机森林回归树的sklearn中的参数含义；


## 代码:构建随机森林回归模型

In [1]:
# import 相关的包
import pandas as pd
from sklearn import preprocessing
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import load_boston

In [13]:
#加载数据
boston_house = load_boston()

##调用数据集中的数据
boston_feature_name = boston_house.feature_names
boston_features = boston_house.data
boston_target = boston_house.target


In [3]:
#查看相关数据
boston_feature_name


array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'],
      dtype='<U7')

In [4]:
#查看数据集的相关信息
print(boston_house.DESCR)

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [6]:
#插卡数据集中的前5行
boston_features[:5,:]

array([[  6.32000000e-03,   1.80000000e+01,   2.31000000e+00,
          0.00000000e+00,   5.38000000e-01,   6.57500000e+00,
          6.52000000e+01,   4.09000000e+00,   1.00000000e+00,
          2.96000000e+02,   1.53000000e+01,   3.96900000e+02,
          4.98000000e+00],
       [  2.73100000e-02,   0.00000000e+00,   7.07000000e+00,
          0.00000000e+00,   4.69000000e-01,   6.42100000e+00,
          7.89000000e+01,   4.96710000e+00,   2.00000000e+00,
          2.42000000e+02,   1.78000000e+01,   3.96900000e+02,
          9.14000000e+00],
       [  2.72900000e-02,   0.00000000e+00,   7.07000000e+00,
          0.00000000e+00,   4.69000000e-01,   7.18500000e+00,
          6.11000000e+01,   4.96710000e+00,   2.00000000e+00,
          2.42000000e+02,   1.78000000e+01,   3.92830000e+02,
          4.03000000e+00],
       [  3.23700000e-02,   0.00000000e+00,   2.18000000e+00,
          0.00000000e+00,   4.58000000e-01,   6.99800000e+00,
          4.58000000e+01,   6.06220000e+00,   3.000

In [7]:
#查看数据集的target
boston_target

array([ 24. ,  21.6,  34.7,  33.4,  36.2,  28.7,  22.9,  27.1,  16.5,
        18.9,  15. ,  18.9,  21.7,  20.4,  18.2,  19.9,  23.1,  17.5,
        20.2,  18.2,  13.6,  19.6,  15.2,  14.5,  15.6,  13.9,  16.6,
        14.8,  18.4,  21. ,  12.7,  14.5,  13.2,  13.1,  13.5,  18.9,
        20. ,  21. ,  24.7,  30.8,  34.9,  26.6,  25.3,  24.7,  21.2,
        19.3,  20. ,  16.6,  14.4,  19.4,  19.7,  20.5,  25. ,  23.4,
        18.9,  35.4,  24.7,  31.6,  23.3,  19.6,  18.7,  16. ,  22.2,
        25. ,  33. ,  23.5,  19.4,  22. ,  17.4,  20.9,  24.2,  21.7,
        22.8,  23.4,  24.1,  21.4,  20. ,  20.8,  21.2,  20.3,  28. ,
        23.9,  24.8,  22.9,  23.9,  26.6,  22.5,  22.2,  23.6,  28.7,
        22.6,  22. ,  22.9,  25. ,  20.6,  28.4,  21.4,  38.7,  43.8,
        33.2,  27.5,  26.5,  18.6,  19.3,  20.1,  19.5,  19.5,  20.4,
        19.8,  19.4,  21.7,  22.8,  18.8,  18.7,  18.5,  18.3,  21.2,
        19.2,  20.4,  19.3,  22. ,  20.3,  20.5,  17.3,  18.8,  21.4,
        15.7,  16.2,

### 构建模型

In [8]:
#查看随机森林回归书的相关帮助文档
help(RandomForestRegressor)

Help on class RandomForestRegressor in module sklearn.ensemble.forest:

class RandomForestRegressor(ForestRegressor)
 |  A random forest regressor.
 |  
 |  A random forest is a meta estimator that fits a number of classifying
 |  decision trees on various sub-samples of the dataset and use averaging
 |  to improve the predictive accuracy and control over-fitting.
 |  The sub-sample size is always the same as the original
 |  input sample size but the samples are drawn with replacement if
 |  `bootstrap=True` (default).
 |  
 |  Read more in the :ref:`User Guide <forest>`.
 |  
 |  Parameters
 |  ----------
 |  n_estimators : integer, optional (default=10)
 |      The number of trees in the forest.
 |  
 |  criterion : string, optional (default="mse")
 |      The function to measure the quality of a split. Supported criteria
 |      are "mse" for the mean squared error, which is equal to variance
 |      reduction as feature selection criterion, and "mae" for the mean
 |      absolute 

In [9]:
#初始化一个随机森林回归树模型，包含15个决策树
rgs = RandomForestRegressor(n_estimators=15)
#训练模型
rgs = rgs.fit(boston_features, boston_target)

In [10]:
rgs

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=15, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [11]:
#随机森林回归树预测结果
rgs.predict(boston_features)

array([ 24.81333333,  22.03333333,  33.46666667,  33.72      ,
        35.68      ,  26.55333333,  21.23333333,  24.48      ,
        18.03333333,  18.6       ,  15.80666667,  19.73333333,
        21.42666667,  19.88      ,  18.86666667,  19.86      ,
        22.7       ,  18.38      ,  19.00666667,  18.42      ,
        14.13333333,  19.77333333,  15.36      ,  14.83333333,
        17.18666667,  14.22666667,  17.16666667,  15.3       ,
        18.86666667,  21.2       ,  14.36666667,  16.54      ,
        14.86      ,  13.36666667,  13.48      ,  19.5       ,
        20.56      ,  21.08666667,  22.48      ,  29.75333333,
        34.55333333,  28.12      ,  25.16666667,  24.88666667,
        21.67333333,  19.48666667,  20.05333333,  17.37333333,
        16.15333333,  18.64      ,  20.18666667,  21.30666667,
        24.42      ,  22.18      ,  18.98666667,  34.86      ,
        24.17333333,  30.98666667,  23.14      ,  19.65333333,
        18.72666667,  17.56      ,  22.62      ,  25.04

In [12]:
#回归树建模
from sklearn import tree
#构建回归树模型
rgs2 = tree.DecisionTreeRegressor()
rgs2.fit(boston_features, boston_target)
#回归树模型的预测结果
rgs2.predict(boston_features)


array([ 24. ,  21.6,  34.7,  33.4,  36.2,  28.7,  22.9,  27.1,  16.5,
        18.9,  15. ,  18.9,  21.7,  20.4,  18.2,  19.9,  23.1,  17.5,
        20.2,  18.2,  13.6,  19.6,  15.2,  14.5,  15.6,  13.9,  16.6,
        14.8,  18.4,  21. ,  12.7,  14.5,  13.2,  13.1,  13.5,  18.9,
        20. ,  21. ,  24.7,  30.8,  34.9,  26.6,  25.3,  24.7,  21.2,
        19.3,  20. ,  16.6,  14.4,  19.4,  19.7,  20.5,  25. ,  23.4,
        18.9,  35.4,  24.7,  31.6,  23.3,  19.6,  18.7,  16. ,  22.2,
        25. ,  33. ,  23.5,  19.4,  22. ,  17.4,  20.9,  24.2,  21.7,
        22.8,  23.4,  24.1,  21.4,  20. ,  20.8,  21.2,  20.3,  28. ,
        23.9,  24.8,  22.9,  23.9,  26.6,  22.5,  22.2,  23.6,  28.7,
        22.6,  22. ,  22.9,  25. ,  20.6,  28.4,  21.4,  38.7,  43.8,
        33.2,  27.5,  26.5,  18.6,  19.3,  20.1,  19.5,  19.5,  20.4,
        19.8,  19.4,  21.7,  22.8,  18.8,  18.7,  18.5,  18.3,  21.2,
        19.2,  20.4,  19.3,  22. ,  20.3,  20.5,  17.3,  18.8,  21.4,
        15.7,  16.2,

In [ ]:
补充知识点---随机森林回归树模型各参数的含义：
函数：class sklearn.ensemble.RandomForestRegressor(n_estimators=10, criterion=’mse’, max_depth=None, min_samples_split=2, min_samples_leaf=1, 
min_weight_fraction_leaf=0.0, max_features=’auto’, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, bootstrap=True, oob_score=False, 
n_jobs=1, random_state=None, verbose=0, warm_start=False)

1.n_estimators：森林中数的个数。 
这个属性是典型的模型表现与模型效率成反比的影响因子，即便如此，你还是应该尽可能提高这个数字，以让你的模型更准确更稳定。 
2.criterion ：度量分裂的标准。可选值：“mse”，均方差（mean squared error）；“mae”，平均绝对值误差（mean absolute error） 
3.max_features ：寻找最佳分裂点时考虑的属性数目。可选值，int（具体的数目），float（数目的百分比），string（“auto”， “sqrt”，“log2”）. 
这一属性是对单个树来设置的，通常来讲，这个值越大单棵树可以考虑的属性越多，则模型的表现就越好。但是这也不是肯定的，不过有一点是肯定的，增加这个值会导致算法运行速度变慢，所以需要我们考虑去达到一个平衡。 
4.max_depth : integer或者None。数的最大深度，如果None，节点扩展直到所有叶子是纯的或者所有叶子节点包含的样例数小于min_samples_split  
5.min_samples_split ： 分裂内部节点需要的最少样例数。int(具体数目),float(数目的百分比) 
6.min_samples_leaf ：叶子节点上应有的最少样例数。int(具体数目),float(数目的百分比)。 
更少的节点数使得模型更容易遭受noise data的影响，我通常设置这个值大于50，但是你需要寻找最适合你的数值。 
7.min_weight_fraction_leaf ： 
8.max_leaf_nodes ：以”最优优先方式”(best-first fashion),最优节点定义为:纯度的相对减少.如果None则不限制叶子节点个数;[float] 
9.min_impurity_split : 树增长提前结束的阈值.对于当前节点,大于这个阈值将分裂,否则就看做叶子节点; [float] 
10.min_impurity_decrease ：一个阈值,表示一个节点分裂的条件是:如果这次分裂纯度的减少大于等于这这个值. 
11.bootstrap ：构建数是不是采用有放回样本的方式(bootstrap samples);  [True/False] 
12.oob_score ：交叉验证相关的属性。 
13.n_jobs ：设定fit和predict阶段并列执行的任务个数,如果设置为-1表示并行执行的任务数等于计算级核数; [integer, optional (default=1)] 
14.random_state ：如果是int数值表示它就是随机数产生器的种子.如果指定RandomState实例,它就是随机产生器的种子.如果是None,随机数产生器是np.random所用的RandomState实例;  [int, RandomState instance or None, optional (default=None)] 
15.verbose ：控制构建数过程的冗长度;  [int, optional (default=0)] 
16.warm_start ：当设置为True,重新使用之前的结构去拟合样例并且加入更多的估计器(estimators,在这里就是随机树)到组合器中; [True/False] 
17.class_weight: “banlanced”模式是根据y标签值自动调整权值与输入数据的类频率成反比,计算公式是:n_samples / (n_classes  np.bincount(y)).“balanced_subsample”模式的与”balanced模式相同,只不过在每一次树增长过程中权值的计算是根据有放回样本的.

补充随机森林的练习：
参考链接1：https://blog.csdn.net/u012559520/article/details/77336098
参考链接2：https://blog.csdn.net/qq_16633405/article/details/61200502
参考链接3：https://www.programcreek.com/python/example/86074/sklearn.ensemble.RandomForestRegressor
参考链接4：https://blog.csdn.net/luoganttcc/article/details/80618336



## 案例总结

1.通过本案例掌握回归树的基本原理；

2.通过本案例加深对随机森林算法的理解；


作者：寒小阳、助教：haoshuai714

本文档版权归稀牛学院所有




![](http://osloyi5le.bkt.clouddn.com/%E7%A8%80%E7%89%9B%20x%20%E7%BD%91%E6%98%93.png)